### ISSUE TITLE
Provide AWS example with external calls

### ISSUE THREAD

**Issue by jasonrichardsmith** [nanovms/ops-examples#86]
While testing Consul, I was attempting to use the Consul as instances by themselves and instances in an ASG. I tried with static and dhcp ips.

Consul has a feature that allows instances to autoregister instances with a specific "tag". This does not work on NanoVMs, because it is unable to make https calls.
When Consul boots it is also incapable of checking for updates, which is also and http call to consul servers.
This has been tested with NanoVMs and an Amazon2 image both with the same Security Groups and InstanceProfile. NanoVMs do not work.

This has only been tested with Go. I have used the same code Consul uses (standard AWS SDK) and no results.
```go
package main

import (
	"fmt"
	"time"

	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/ec2"
)

func main() {
	fmt.Println("vim-go")
	region := "eu-west-1"

	svc := ec2.New(session.New(), &aws.Config{
		Region: &region,
	})
	for {
		resp, err := svc.DescribeInstances(&ec2.DescribeInstancesInput{})
		if err != nil {
			fmt.Printf("discover-aws: DescribeInstances failed: %s", err)
		} else {
			fmt.Println(resp)
		}
		time.Sleep(10 * time.Second)
	}

}
```

Error logs
```
ops instance logs awssdktest-1642503817 -t aws -z eu-west-1
en1: assigned 192.168.1.38
vim-go
en1: assigned FE80::437:D3FF:FE2C:B4F1
discover-aws: DescribeInstances failed: RequestError: send request failed
caused by: Post "https://ec2.eu-west-1.amazonaws.com/": dial tcp 54.239.39.230:443: connect: invalid argumentdiscover-aws: DescribeInstances failed: RequestError: send request failed
caused by: Post "https://ec2.eu-west-1.amazonaws.com/": dial tcp 54.239.35.17:443: connect: invalid argument%
```

```ops instance``` also does not allow referencing Instance profiles, so currently aws credentials have to be assigned in the config.json.

```json
{
  "CloudConfig": {
	  "Zone": "eu-west-1",
	  "Platform": "aws",
	  "BucketName":"yourbucket",
        "VPC": "vpc-00000000000000",
        "SecurityGroup": "sg-00000000000"
  },
  "NameServer": "192.168.0.2",
  "Env": {
	"AWS_ACCESS_KEY": "************************",
	"AWS_SECRET_ACCESS_KEY": "***************************************************"
	}
}
```

Locally images do work.  In AWS they do not.

**Comment by jasonrichardsmith** [comment]
This is the tree for the image created locally.

```bash
ops image tree awssdktest                   10324  12:40:52 
/
|   lib64
|   |   ld-linux-x86-64.so.2
|   lib
|   |   x86_64-linux-gnu
|   |   |   libc.so.6
|   |   |   libnss_dns.so.2
|   |   |   libpthread.so.0
|   etc
|   |   resolv.conf
|   |   passwd
|   |   ssl
|   |   |   certs
|   |   |   |   ca-certificates.crt
|   awssdktest
|   proc
|   |   sys
|   |   |   kernel
|   |   |   |   hostname
```

**Comment by jasonrichardsmith** [comment]
The stack where this was deployed.
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: 'VPC with Public subnets'
Parameters:
  AMI:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/test/awssdk'

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: '192.168.1.0/21'
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'

  PubSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref 'VPC'
      AvailabilityZone: !Select [0, !GetAZs ""]
      CidrBlock: '192.168.1.0/24'


  PubRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC


  PubRouteTableAssoc1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    DependsOn:
      - PubSubnet1
      - PubRouteTable
    Properties:
      SubnetId: !Ref 'PubSubnet1'
      RouteTableId: !Ref 'PubRouteTable'


  Gateway:
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref Gateway


  PubRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PubRouteTable
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId: !Ref Gateway


  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: DescribeInstances
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ec2:DescribeInstances
                Resource: '*'
  Profile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref Role

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'awssdktest'
      VpcId: !Ref VPC
      SecurityGroupIngress:
      - IpProtocol: -1
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: -1
        CidrIp: 0.0.0.0/0

  Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !Ref AMI
      SecurityGroupIds:
      - !Ref SecurityGroup
      SubnetId: !Ref PubSubnet1
      IamInstanceProfile: !Ref Profile
      BlockDeviceMappings:
      - DeviceName: "/dev/sda1"
        Ebs:
          VolumeType: "gp2"
          DeleteOnTermination: "true"
          VolumeSize: "8"
```
